CREATE TABLE IF NOT EXISTS TURNOS (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    CATEGORIA VARCHAR(255),
    MESA VARCHAR(255),
    CONTADOR INTEGER,
    MAXIMOCONTADOR INTEGER,
    ULTIMAMODIFICACION DATE
);
